### ISSUE TITLE
Option to configure or display mappings and build version being used (1.12.2)

### ISSUE THREAD

**Issue by mica-alex** [GregTechCEu/Buildscripts#84]
In migrating an existing mod from a broken ForgeGradle setup, I've run in to an issue where, I believe, the mappings are causing compilation issues. 

The existing mod Gradle setup has `mappings channel: 'snapshot', version: '20171003-1.12'` and `minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2860'`

Is there a way to change these using `gradle.properties` and/or can you advise what the default mappings and Forge 1.12 build version are?

**Comment by serenibyss** [comment]
it uses forge 2847 and mappings stable_39. There's no way to change it, but its advised to update your code to the stable mappings anyway. [This](https://mcp.thiakil.com/#/search) is a useful source for comparing old mappings to new. It should not be very many changes that you'll need to make though. The forge version discrepancy won't affect anything
